name: merge-to-main

on:
    push:
        branches:
            - main

jobs:
    merge-to-main:
        name: merge-to-main
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}
            - name: node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
            - name: install
              run: npm ci
            - name: lint
              run: npm run lint
            - name: format
              run: npm run format
            - name: test
              run: npm test
            - name: build
              run: npm run build
            - name: release
              run: npm run release:qa
            - name: tag
              run: git push --follow-tags origin main
