name: release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    release:
        name: release
        runs-on: ubuntu-18.04
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
            - name: install
              run: npm ci
            - name: lint
              run: npm run lint
            - name: format
              run: npm run format
            - name: test
              run: npm test
            - name: build
              run: npm run build
            - name: release
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
